### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined when observe(document, ...)

### ISSUE THREAD

**Issue by RickyChien** [megawac/MutationObserver.js#13]
When I invoke 
```javascript
myObserver.observe(document, { attributes: true, characterData: true, childList: true, subtree: true });
```

I got the following errors
```
TypeError: Cannot read property 'length' of undefined
    at reduce (/Users/Ricky/Documents/gaia/node_modules/mutationobserver-shim/MutationObserver.js:537:40)
    at copy (/Users/Ricky/Documents/gaia/node_modules/mutationobserver-shim/MutationObserver.js:462:38)
    at clone (/Users/Ricky/Documents/gaia/node_modules/mutationobserver-shim/MutationObserver.js:479:11)
    at createMutationSearcher (/Users/Ricky/Documents/gaia/node_modules/mutationobserver-shim/MutationObserver.js:173:25)
    at Object.MutationObserver.MutationObserver.WebKitMutationObserver.MutationObserver.observe (/Users/Ricky/Documents/gaia/node_modules/mutationobserver-shim/MutationObserver.js:105:21)
```
I think problem arise from [1]. `$target.attributes` means `document.attributes`, but we don't have any `document.attributes` and throw error. We should give a empty object if someone try to observe document.

[1] https://github.com/megawac/MutationObserver.js/blob/master/MutationObserver.js#L462

**Comment by megawac** [comment]
Thanks, wasn't aware observing `document` was legal

**Comment by megawac** [comment]
Whoops, well that worked in some browsers. Probably will have to add a similar check for `characterData` as well, so I'll leave it open til I can confirm a fix on both

**Comment by megawac** [comment]
Hmmm, [I've run an issue with spec implementations I think for charData on subtree](http://git.ygrae.me/snippets/1) (might be me making an incorrect assumption)
